spring: #띄어쓰기 없음
#  datasource: #띄어쓰기 2칸
#    url: jdbc:h2:tcp://localhost/~/jpashop #4칸
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa: #띄어쓰기 2칸
#    hibernate: #띄어쓰기 4칸
#      ddl-auto: create #띄어쓰기 6칸
#    properties: #띄어쓰기 4칸
#      hibernate: #띄어쓰기 6칸
#        # show_sql: true #띄어쓰기 8칸
#        format_sql: true #띄어쓰기 8칸
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.31.36.42:3306/party_together?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 362405
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

